### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by vrmartins** [vrmartins/poc-django-rest-framework#2]
### Tasks

- [x] Configure Django
- [x] Configure Django Rest Framework
- [x] Configure Makefile
- [x] Configure requirements and requirements-to-freeze
- [x] Create Customer endpoint
- [x] Configure Input validation
- [ ] Create Customer by CNPJ (with fallback origin) with cache (Redis)
- [ ] Automate freeze requirements when install new deps
- [ ] Configure Swagger or similar
- [ ] Configure logger
- [ ] Configure PyLint
- [ ] Fix: `You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set`
- [ ] Integrate with Postegres
- [ ] Create Dockerfile
- [ ] Create Docker-compose file (App, Postgres, Redis)
- [ ] Configure PyTest
- [ ] Configure Coverage Code Test
- [ ] Implement error handling
- [ ] Implement security components
- [ ] Configure JWT
- [ ] Configure Multi Tenancy
- [ ] To sanitize inputs
- [ ] Create User endpoint
- [ ] Create Tenant endpoint
- [ ] Include Tenant in customer
- [ ] Update README.md
- [ ] Implement Google Login
- [ ] Implement Facebook Login
